package com.turbolego.songguesser

import org.json.JSONArray
import org.json.JSONObject
import java.security.SecureRandom
import java.util.Base64
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * Canonical message types and JSON helpers for the GuessTheSongYear multiplayer protocol.
 *
 * All networked messages are newline-delimited JSON (one JSON object per line)
 * over a reliable transport (TCP or Bluetooth RFCOMM).
 *
 * Protocol flow:
 *   1. Client → Host: JOIN {type, player}
 *   2. Host → Client: JOIN_ACK {type, sessionId, hostName, sessionKey, players[], currentVideoId?, currentYear?, currentTitle?}
 *   3. Host → All:  VIDEO {type, id, year, title, sig}  (when a new video loads)
 *   4. Host → All:  PLAYER_LIST {type, players[], sig}   (scores updated)
 *   5. Host → All:  REVEAL {type, sig}                    (host pressed "Vis svar")
 *   6. Client → Host: GUESS_BLIND {type, player, guess, sig}  (sent after REVEAL)
 *   7. Host → Client: REVEAL_RESULT {type, results[{player, guess, correctYear, pointsEarned, difference, isCorrect, totalScore}], leaderboard[{name, score}], sig}
 *   8. Host → All:  PLAYER_LEFT {type, player, sig}
 *   9. Host → All / Client → Host: END {type, player?, sig}
 *
 * Message signing:
 *   All messages after JOIN_ACK include a `sig` field containing an HMAC-SHA256
 *   of the JSON body (excluding the `sig` field itself). The session key is randomly
 *   generated by the host and shared in the JOIN_ACK.response.
 */
object Protocol {

    // ── Message type constants ───────────────────────────────────────────────

    const val MSG_JOIN = "JOIN"
    const val MSG_JOIN_ACK = "JOIN_ACK"
    const val MSG_PLAYER_LIST = "PLAYER_LIST"
    const val MSG_VIDEO = "VIDEO"
    const val MSG_REVEAL = "REVEAL"
    const val MSG_GUESS_BLIND = "GUESS_BLIND"
    const val MSG_REVEAL_RESULT = "REVEAL_RESULT"
    const val MSG_PLAYER_LEFT = "PLAYER_LEFT"
    const val MSG_END = "END"
    const val MSG_HELLO = "HELLO"
    const val MSG_ACK = "ACK"

    // ── JSON field constants ─────────────────────────────────────────────────

    const val FIELD_TYPE = "type"
    const val FIELD_PLAYER = "player"
    const val FIELD_PLAYERS = "players"
    const val FIELD_SESSION_ID = "sessionId"
    const val FIELD_HOST_NAME = "hostName"
    const val FIELD_VIDEO_ID = "id"
    const val FIELD_YEAR = "year"
    const val FIELD_TITLE = "title"
    const val FIELD_GUESS = "guess"
    const val FIELD_CORRECT_YEAR = "correctYear"
    const val FIELD_POINTS_EARNED = "pointsEarned"
    const val FIELD_DIFFERENCE = "difference"
    const val FIELD_IS_CORRECT = "isCorrect"
    const val FIELD_SCORE = "score"
    const val FIELD_TOTAL_SCORE = "totalScore"
    const val FIELD_NAME = "name"
    const val FIELD_IS_HOST = "isHost"
    const val FIELD_RESULTS = "results"
    const val FIELD_LEADERBOARD = "leaderboard"
    const val FIELD_CURRENT_VIDEO_ID = "currentVideoId"
    const val FIELD_CURRENT_YEAR = "currentYear"
    const val FIELD_CURRENT_TITLE = "currentTitle"
    const val FIELD_CURRENT_PLAYER_INDEX = "currentPlayerIndex"
    const val FIELD_CURRENT_PLAYER = "currentPlayer"
    const val FIELD_PLAYER_NAMES = "playerNames"

    // ── Transport type constants ─────────────────────────────────────────────

    const val TRANSPORT_WIFI = "wifi"
    const val TRANSPORT_BLUETOOTH = "bluetooth"
    const val TRANSPORT_TLS = "tls"

    // ── Service constants ────────────────────────────────────────────────────

    /** Default TCP server port for Wi-Fi transport. */
    const val WIFI_SERVER_PORT = 8888

    /** TLS-only port — host also listens here for secure clients. */
    const val WIFI_TLS_SERVER_PORT = 8889

    /** Bluetooth RFCOMM service name (used for SDP record). */
    const val BT_SERVICE_NAME = "GuessTheSongYear"

    /** Bluetooth RFCOMM service UUID (random, must match on host + join). */
    const val BT_SERVICE_UUID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    // ── Timeouts ──────────────────────────────────────────────────────────────

    const val SOCKET_TIMEOUT_MS = 30_000
    const val CONNECT_TIMEOUT_MS = 15_000
    const val RECONNECT_DELAY_MS = 3_000L
    const val MAX_RECONNECT_ATTEMPTS = 3

    // ── TLS / Secure channel ──────────────────────────────────────────────────

    /** Message type: TLS HELLO (initiates secure upgrade over plain socket). */
    const val MSG_TLS_HELLO = "TLS_HELLO"

    /** JSON field: Base64-encoded SPKI hash for certificate pinning. */
    const val FIELD_TLS_SPKI_HASH = "tlsSpkiHash"

    /** JSON field: Base64-encoded HMAC-SHA256 signature. */
    const val FIELD_SIG = "sig"

    /** JSON field: Base64-encoded session key (shared in JOIN_ACK). */
    const val FIELD_SESSION_KEY = "sessionKey"

    // ── Message signing ──────────────────────────────────────────────────────

    /**
     * Message authenticator using HMAC-SHA256.
     *
     * The session key is generated by the host and shared with each client in
     * the JOIN_ACK message. All subsequent messages include a `sig` field
     * computed as:
     *   HMAC-SHA256(sessionKey, message-without-sig-field)
     */
    class MessageAuthenticator(private val keyBytes: ByteArray) {

        private val mac: Mac = Mac.getInstance(HMAC_ALGORITHM).apply {
            init(SecretKeySpec(keyBytes, HMAC_ALGORITHM))
        }

        /**
         * Signs a JSON message by adding a `sig` field.
         *
         * @param json  The JSONObject to sign. The `sig` field (if present) is removed first.
         * @return The same JSONObject instance with `sig` set.
         */
        fun sign(json: JSONObject): JSONObject {
            json.remove(FIELD_SIG)
            val bodyBytes = json.toString().toByteArray(Charsets.UTF_8)
            val hash = mac.doFinal(bodyBytes)
            json.put(FIELD_SIG, Base64.getEncoder().encodeToString(hash))
            return json
        }

        /**
         * Verifies that a received JSON message has a valid HMAC signature.
         *
         * @param json The received JSONObject.
         * @return true if the signature is valid or if the message has no `sig` field
         *         (backward compatibility for plain-text mode without signing).
         */
        fun verify(json: JSONObject): Boolean {
            val receivedSig = json.optString(FIELD_SIG, null) ?: return true // no sig → old client, allow
            val bodyJson = JSONObject(json.toString()).apply { remove(FIELD_SIG) }
            val bodyBytes = bodyJson.toString().toByteArray(Charsets.UTF_8)
            val expectedHash = mac.doFinal(bodyBytes)
            val expectedSig = Base64.getEncoder().encodeToString(expectedHash)
            return java.security.MessageDigest.isEqual(
                expectedSig.toByteArray(Charsets.UTF_8),
                receivedSig.toByteArray(Charsets.UTF_8)
            )
        }
    }

    /**
     * Generate a 32-byte random session key, encoded as Base64.
     */
    fun generateSessionKey(): String {
        val key = ByteArray(32)
        SecureRandom().nextBytes(key)
        return Base64.getEncoder().encodeToString(key)
    }

    /**
     * Create a [MessageAuthenticator] from a Base64-encoded session key string.
     */
    fun createAuthenticator(sessionKeyBase64: String): MessageAuthenticator {
        val keyBytes = Base64.getDecoder().decode(sessionKeyBase64)
        return MessageAuthenticator(keyBytes)
    }

    /** Private MAC instances per authenticator (not thread-safe; use per-connection). */
    private const val HMAC_ALGORITHM = "HmacSHA256"

    // ── JSON helpers ─────────────────────────────────────────────────────────

    /** Convenience builder for [JSONObject]. */
    inline fun buildJson(block: JSONObject.() -> Unit): JSONObject =
        JSONObject().apply(block)

    /** Convenience builder for [JSONArray]. */
    inline fun buildJsonArray(block: JSONArray.() -> Unit): JSONArray =
        JSONArray().apply(block)

    /**
     * Safely parse a JSON string, returning null on any parse error.
     */
    fun tryParse(json: String): JSONObject? =
        try {
            JSONObject(json)
        } catch (_: Exception) {
            null
        }
}
