#!/usr/bin/env python3
"""
Refresh the music_videos.txt asset file by scraping YouTube's public RSS feeds.
Uses yt-dlp to search for popular music videos by year.
No API keys needed — YouTube RSS feeds are public, no auth required.

Run locally:
    pip install yt-dlp
    python scripts/refresh_videos.py

Or via GitHub Actions (weekly cron).
"""

import subprocess
import os
import sys
from collections import OrderedDict

ASSET_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "app", "src", "main", "assets", "music_videos.txt"
)
YEARS = list(range(1980, 2026))
VIDEOS_PER_YEAR = 15


def fetch_videos_by_year(year: int) -> list[tuple[str, str]]:
    """Fetch popular music videos for a given year using yt-dlp."""
    query = f"popular songs {year} music"
    cmd = [
        "yt-dlp",
        f"ytsearch{VIDEOS_PER_YEAR}:{query}",
        "--print", "%(id)s,%(title)s",
        "--no-warnings",
        "--ignore-errors",
        "--flat-playlist",
    ]
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120
        )
        videos = []
        for line in result.stdout.strip().split("\n"):
            line = line.strip()
            if not line or "," not in line:
                continue
            parts = line.split(",", 1)
            if len(parts) == 2 and parts[0]:
                videos.append((parts[0].strip(), parts[1].strip()))
                print(f"  {year}: {parts[0]} — {parts[1][:50]}")
        return videos
    except subprocess.TimeoutExpired:
        print(f"  Timeout fetching year {year}")
        return []
    except Exception as e:
        print(f"  Error fetching year {year}: {e}")
        return []


def main():
    # Read existing entries to preserve manual additions
    existing = OrderedDict()
    header_lines = []
    if os.path.exists(ASSET_PATH):
        with open(ASSET_PATH, encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith("#"):
                    header_lines.append(line)
                elif stripped and "," in stripped:
                    vid = stripped.split(",")[0].strip()
                    existing[vid] = stripped

    print(f"Existing entries: {len(existing)}")
    print("Fetching fresh videos by year...")

    new_count = 0
    for year in YEARS:
        videos = fetch_videos_by_year(year)
        for vid_id, title in videos:
            if vid_id not in existing:
                # Clean title: strip quotes, limit commas
                clean_title = title.replace('"', "").replace("'", "")
                existing[vid_id] = f"{vid_id},{year},{clean_title}"
                new_count += 1

    # Write updated file
    with open(ASSET_PATH, "w", encoding="utf-8") as f:
        for h in header_lines:
            f.write(h)
        f.write(f"# Auto-updated: {len(existing)} entries ({new_count} new)\n")
        f.write("# Format: videoId,year,title\n")
        f.write("# Generated by scripts/refresh_videos.py\n\n")
        for entry in existing.values():
            f.write(entry + "\n")

    print(f"\nDone: {len(existing)} total entries ({new_count} new)")


if __name__ == "__main__":
    main()
